### PR TITLE
Fault in numbering

### PR DESCRIPTION
**Pull request by sebie**
Simple mistake I noticed whilst reading your code; you can change it yourself (if it is easier) or merge the branches.

### CODE REVIEW

**Comment by gynter** [comment]
Heh yea, must have made a mistake when re-ordering the sections there, thanks for the fix!

**Comment by sebie** [comment]
No problem! You already helped me on IRC; so just returning the favour.

By the way, could you help clear something up for me?

* Is it possible to put liquid tags and markdown in a `.txt` and having rendered?
* Can you put markdown in HTML elements? (*Example below*)

```markdown
<p>*Lorem* **Ipsum**</p>
```

**Comment by gynter** [comment]
Afaik it's not possible to do that. I recommend to post this kind of stuff to <https://talk.jekyllrb.com/>.

**Comment by sebie** [comment]
Ok, fair enough. Have a great day!

**Pull request merged**
